export const technologies = [
  { iconName: "devicon-typescript-original", name: "TypeScript" },
  { iconName: "devicon-javascript-plain", name: "JavaScript" },
  { iconName: "devicon-nodejs-plain", name: "Node.js" },
  { iconName: "devicon-java-plain", name: "Java" },
  { iconName: "devicon-bash-plain", name: "Bash" },
  { iconName: "devicon-react-original", name: "React Native" },
  { iconName: "devicon-nextjs-original", name: "Next.js" },
  { iconName: "devicon-vuejs-plain", name: "Vue.js" },
  { iconName: "devicon-electron-original", name: "Electron" },
  { iconName: "devicon-react-original", name: "React.js" },
  { iconName: "devicon-html5-plain", name: "HTML" },
  { iconName: "devicon-css3-plain", name: "CSS" },
  { iconName: "devicon-sass-original", name: "SASS" },
  { iconName: "devicon-threejs-original", name: "Three.js" },
  { iconName: "devicon-tailwindcss-plain", name: "Tailwind" },
  { iconName: "devicon-docker-plain", name: "Docker" },
  { iconName: "devicon-npm-original-wordmark", name: "NPM" },
  { iconName: "devicon-webpack-plain", name: "Webpack" },
  { iconName: "devicon-babel-original", name: "Babel" },
  { iconName: "devicon-git-plain", name: "Git" },
  { iconName: "devicon-postgresql-plain", name: "PostgreSQL" },
  { iconName: "devicon-mongodb-plain", name: "MongoDB" },
  { iconName: "devicon-amazonwebservices-original", name: "AWS" },
  { iconName: "devicon-redis-plain", name: "Redis" },
  { iconName: "devicon-figma-plain", name: "Figma" },
];
